[build]
command = "npm run build"
publish = "/dist"
base = "/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[edge_functions]]
  path = "/"
  function = "set-metas-by-lang"

  [[edge_functions]]
  path = "/(pt|en|es|fr|de)"
  function = "set-metas-by-lang"